### ISSUE TITLE
[BUG]: --dry is making changes

### ISSUE THREAD

**Issue by kevinsperrine** [sensedeep/onetable-cli#12]
**Describe the bug**
I'm confused why a `--dry` run is actually making changes to the table and calling the up/down functions in lambda.

**To Reproduce**
command and output:
```js
$> onetable --profile sandbox --verbose --debug --dry up
Using configuration profile "sandbox"
Accessing DynamoDb "single-table-test-dev-SingleTableTest-C9AGMOK7KZ2H" via proxy at arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:single-table-test-dev-migrate
Invoke migrate proxy {
  action: 'getCurrentVersion',
  args: undefined,
  arn: 'arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:single-table-test-dev-migrate'
}
Migrate proxy results { args: undefined, result: '0.0.0' }
Invoke migrate proxy {
  action: 'getOutstandingVersions',
  args: undefined,
  arn: 'arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:single-table-test-dev-migrate'
}
Migrate proxy results { args: undefined, result: [ '0.0.1', '0.0.2', '0.0.2' ] }
Invoke migrate proxy {
  action: 'findPastMigrations',
  args: undefined,
  arn: 'arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:single-table-test-dev-migrate'
}
Migrate proxy results { args: undefined, result: [] }
Dry Run:  upgrade 1 change to version 0.0.1.

Migrations to apply:
0.0.1

Invoke migrate proxy {
  action: 'apply',
  args: { direction: 1, version: '0.0.1' },
  arn: 'arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:single-table-test-dev-migrate'
}
Migrate proxy results { args: { direction: 1, version: '0.0.1' }, result: undefined }
TypeError: Cannot read properties of undefined (reading 'version')
    at CLI.move (file:///usr/local/lib/node_modules/onetable-cli/dist/cli.js:313:45)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CLI.command (file:///usr/local/lib/node_modules/onetable-cli/dist/cli.js:181:17)
    at async main (file:///usr/local/lib/node_modules/onetable-cli/dist/cli.js:549:9)
Migration failed Cannot read properties of undefined (reading 'version') undefined
```

**Expected behavior**
I wouldn't expect any changes to the data.

**Screenshots**

**Environment (please complete the following information):**
 - OS Mac Mojave
 - Node Version 16.13.0

**Additional context**
migration.json
```json
{
  "profiles": {
    "sandbox": {
      "arn": "arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:single-table-test-dev-migrate",
      "onetable": {
        "typeField": "type",
        "name": "single-table-test-dev-SingleTableTest-C9AGMOK7KZ2H",
        "delimiter": "#",
        "createdField": "createdAt",
        "updatedField": "updatedAt",
        "timestamps": true,
        "isoDates": true
      },
      "aws": {
        "region": "us-east-1"
      }
    }
  }
}

```

schema-0.0.1
```js
{
  version: "0.0.1",
  indexes: {
    primary: { hash: "PK", sort: "SK" },
  },
  models: {
    Organization: {
      PK: { type: String, value: "ORG#${id}" },
      SK: { type: String, value: "ORG#${id}" },
      id: { type: String, uuid: true, validate: MATCH.ksuid },
      type: { type: String, value: "organization" },
      name: { type: String, required: true },
    },
  },
}
```

schema-0.0.2
```js
{
  version: "0.0.2",
  indexes: {
    primary: { hash: "PK", sort: "SK" },
    GSI1: { hash: "GSI1PK", sort: "GSI1SK", follow: true },
  },
  models: {
    Organization: {
      PK: { type: String, value: "ORG#${id}" },
      SK: { type: String, value: "ORG#${id}" },
      id: { type: String, uuid: true, validate: MATCH.ksuid },
      type: { type: String, value: "organization" },
      name: { type: String, required: true },
      GSI1PK: { type: String, value: "ORG#" },
      GSI1SK: { type: String, value: "ORG#${name}#${id}" },
    },
    User: {
      PK: { type: String, value: "ORG:${orgId}" },
      SK: { type: String, value: "USER:${email}", validate: MATCH.email },
      id: { type: String, uuid: true, validate: MATCH.ksuid },
      orgId: { type: String, required: true },
      email: { type: String, required: true },
      name: { type: String, required: true },
      username: { type: String, required: true },
      role: {
        type: String,
        enum: ["USER", "ADMIN"],
        required: true,
        default: "USER",
      },
      GSI1PK: { type: String, value: "USER_EMAIL:${email}" },
      GSI1SK: { type: String, value: "USER:" },
    },
  },
}
```

the two entries created in dynamo
```js
[
  {
    "version": "0.0.1",
    "params": {
      "createdField": "createdAt",
      "hidden": true,
      "updatedField": "updatedAt",
      "timestamps": true,
      "nulls": false,
      "isoDates": true,
      "typeField": "type"
    },
    "updatedAt": "2021-11-13T11:11:10.032Z",
    "queries": {},
    "SK": "_schema:Current",
    "indexes": {
      "primary": {
        "hash": "PK",
        "sort": "SK"
      }
    },
    "models": {
      "Organization": {
        "SK": {
          "type": "string",
          "value": "ORG#${id}"
        },
        "name": {
          "type": "string",
          "required": true
        },
        "PK": {
          "type": "string",
          "value": "ORG#${id}"
        },
        "id": {
          "type": "string",
          "uuid": true,
          "validate": "/^[a-zA-Z0-9]{27}$/i"
        },
        "type": {
          "type": "string",
          "value": "organization"
        }
      }
    },
    "PK": "_schema",
    "name": "Current",
    "format": "onetable:1.0.0",
    "type": "_Schema"
  },
  {
    "version": "0.0.1",
    "date": "2021-11-13T11:11:10.035Z",
    "path": "memory",
    "updatedAt": "2021-11-13T11:11:10.035Z",
    "createdAt": "2021-11-13T11:11:10.035Z",
    "SK": "_migration:0.0.1",
    "description": "Test migration 0.0.1",
    "PK": "_migration",
    "type": "_Migration"
  }
]
```

excerpt of cloudwatch logs
```
2021-11-13T06:11:10.005-05:00	START RequestId: cc76cd03-6cc9-4555-a76b-3fff44ea6dd0 Version: $LATEST

2021-11-13T06:11:10.008-05:00	2021-11-13T11:11:10.008Z cc76cd03-6cc9-4555-a76b-3fff44ea6dd0 INFO Migrate command apply { event: { action: 'apply', config: { typeField: 'type', name: 'single-table-test-dev-SingleTableTest-C9AGMOK7KZ2H', delimiter: '#', createdField: 'createdAt', updatedField: 'updatedAt', timestamps: true, isoDates: true }, args: { direction: 1, version: '0.0.1' } }, config: { typeField: 'type', name: 'single-table-test-dev-SingleTableTest-C9AGMOK7KZ2H', delimiter: '#', createdField: 'createdAt', updatedField: 'updatedAt', timestamps: true, isoDates: true } }

2021-11-13T06:11:10.008-05:00	2021-11-13T11:11:10.008Z cc76cd03-6cc9-4555-a76b-3fff44ea6dd0 INFO Migrations for single-table-test-dev-SingleTableTest-C9AGMOK7KZ2H { migrations: [ { version: '0.0.1', description: 'Test migration 0.0.1', schema: [Object], up: [AsyncFunction: up], down: [AsyncFunction: down] }, { version: '0.0.2', description: 'Test migration 0.0.2', schema: [Object], up: [AsyncFunction: up], down: [AsyncFunction: down] }, { version: '0.0.2', description: 'Test migration 0.0.2', schema: [Object], up: [AsyncFunction: up], down: [AsyncFunction: down] } ] }

2021-11-13T06:11:10.031-05:00	2021-11-13T11:11:10.031Z cc76cd03-6cc9-4555-a76b-3fff44ea6dd0 INFO Migrate upgrade 0.0.1 "apply"

2021-11-13T06:11:10.031-05:00	2021-11-13T11:11:10.031Z cc76cd03-6cc9-4555-a76b-3fff44ea6dd0 INFO Apply migration 0.0.1 direction 1
```

**Comment by mobsense** [comment]
Thanks for reporting.

Dry run was originally just for the cli and local migrations when the CLI only supported local migrations.  However, now, with remote migrations, "dry" mode needs completion and clarifying. Your issue is good prompting to finish this.

Basically, a dry run should run the selected migrations but with a params.dry == true so that up/down scripts can NOT do updates AND the list of applied migrations should not be updated.

To implement this, we need to add a params 3rd argument to the up() and down() migration scripts. Then the up/down functions can test params.dry and if true, implement a dry run by not doing any updates.

To be useful, a dry run should iterate over all items that would normally be considered in the up/down operation and log what it would normally do. That way then you can run a dry run, check the log and see if it would do the right then, then re-run without dry == true.

This will need updates to onetable-migrate, onetable-cli and onetable-controller to add the params and update the doc/samples. SenseDeep will also need to add a dry-run flag to their migration manager.

We'll start this process.

**Comment by kevinsperrine** [comment]
Thanks, @mobsense. It seems like you all have created a terrific set of tools for interacting with single table dynamo applications. I'm trying to wrap my head around how to set it up, all of it's features and capabilities and this issue came up. Thanks for all the hard work! I'll check out sensedeep more at some point, too.
